<a href="https://colab.research.google.com/github/whyzotee/programming-fundamental/blob/main/Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

รหัสนักศึกษา : 67015026 ชื่อ : นาย ฉัตรนรินทร บุญแสง

Exercise 5.1 ให้เขียน function ชื่อ day_of_year(day, month ,year) โดยมีการคืนค่า คือ day_of_years เป็นวันที่ลำดับที่เท่าใดของปีคริสตศักราช year
ปีที่เป็น Leap Year เดือนกุมภาพันธ์จะมี 29 วัน
ให้สร้างฟังก์ชัน is_leap เพื่อตรวจสอบ leap year แยกออกมา และให้ฟังก์ชัน day_of_year เรียกใช้ is_leap อีกที


In [ ]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
  year_str = str(year)
  year_only_first = year_str[0]+ "0"*(len(year_str[1:]))

  if year % 4 == 0 and year % 100 == 0 and year % 400 == 0:
    return True
  elif year % 4 == 0 and year % 100 != 0 and int(year_only_first) % 400 == 0:
    return True
  else:
    return False


def day_of_year(day, month, year):
  is_leap_year = leap_year(year)

  all_days = day

  if month > 1:
    all_days += sum(days_in_month[:month - 1])

  if is_leap_year and month > 2:
      all_days += 1

  return all_days

# Testcases
print("Normal year (2023):")
print(f"1 Jan 2023: {day_of_year(1, 1, 2023)}")  # ควรได้ 1
print(f"1 Feb 2023: {day_of_year(1, 2, 2023)}")  # ควรได้ 32
print(f"1 Mar 2023: {day_of_year(1, 3, 2023)}")  # ควรได้ 60
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

print("\nLeap year (2024):")
print(f"1 Jan 2024: {day_of_year(1, 1, 2024)}")  # ควรได้ 1
print(f"29 Feb 2024: {day_of_year(29, 2, 2024)}")  # ควรได้ 60
print(f"1 Mar 2024: {day_of_year(1, 3, 2024)}")  # ควรได้ 61
print(f"31 Dec 2024: {day_of_year(31, 12, 2024)}")  # ควรได้ 366

print("\nCentury year, not a leap year (1900):")
print(f"1 Mar 1900: {day_of_year(1, 3, 1900)}")  # ควรได้ 60

print("\nCentury year, leap year (2000):")
print(f"1 Mar 2000: {day_of_year(1, 3, 2000)}")  # ควรได้ 61

print("\nMid-year dates:")
print(f"15 Jun 2023: {day_of_year(15, 6, 2023)}")  # ควรได้ 166
print(f"15 Jun 2024: {day_of_year(15, 6, 2024)}")  # ควรได้ 167 (Leap year)

print("\nLast day of each quarter:")
print(f"31 Mar 2023: {day_of_year(31, 3, 2023)}")  # ควรได้ 90
print(f"30 Jun 2023: {day_of_year(30, 6, 2023)}")  # ควรได้ 181
print(f"30 Sep 2023: {day_of_year(30, 9, 2023)}")  # ควรได้ 273
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

Normal year (2023):
1 Jan 2023: 1
1 Feb 2023: 32
1 Mar 2023: 60
31 Dec 2023: 365

Leap year (2024):
1 Jan 2024: 1
29 Feb 2024: 60
1 Mar 2024: 61
31 Dec 2024: 366

Century year, not a leap year (1900):
1 Mar 1900: 60

Century year, leap year (2000):
1 Mar 2000: 61

Mid-year dates:
15 Jun 2023: 166
15 Jun 2024: 167

Last day of each quarter:
31 Mar 2023: 90
30 Jun 2023: 181
30 Sep 2023: 273
31 Dec 2023: 365


Exercise 5.2 ให้เขียนฟังก์ชัน เพิ่มเติมเป็น date_diff
รับข้อมูลในรูปแบบ “dd-mm-yyyy” เช่น date_diff(“1-1-2018”, “1-1-2020”) จะได้ 731 วัน date_diff(“25-12-1999”, “9-3-2000”) จะได้ 76 วัน
ให้เขียนฟังก์ชัน day_in_year โดยจะส่งค่าจำนวนวันของปี (365 หรือ 366) โดยรับข้อมูลเป็น ปี
ส่งคืนข้อมูลเป็นจำนวนวันตั้งแต่วันที่แรก จนถึงวันที่สอง โดยรวมทั้ง 2 วันนั้นเข้าไปด้วย
ให้สมมติว่าวันแรก จะต้องมาก่อนวันที่สองเสมอ ดังนั้นไม่ต้องตรวจสอบ


In [ ]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
  year_str = str(year)
  year_only_first = year_str[0]+ "0"*(len(year_str[1:]))

  if year % 4 == 0 and year % 100 == 0 and year % 400 == 0:
    return True
  elif year % 4 == 0 and year % 100 != 0 and int(year_only_first) % 400 == 0:
    return True
  else:
    return False

def day_of_year_from_start(day, month, year):
  is_leap_year = leap_year(year)

  sum_of_days = 0

  if day == 1 and month == 1:
    sum_of_days += sum(days_in_month)
  else:
    sum_of_days += (days_in_month[month - 1] - day) + 1
    sum_of_days += sum(days_in_month[month:])

  if is_leap_year and month <= 2:
      sum_of_days += 1

  return sum_of_days

def day_of_year_from_end(day, month, year):
  is_leap_year = leap_year(year)

  sum_of_days = sum(days_in_month[:month - 1]) + day

  if is_leap_year and month > 2:
      sum_of_days += 1

  return sum_of_days

def calculate_n_year(start_year,year_count):
  sum = 0
  for i in range(1, year_count):
    sum += day_of_year_from_start(1, 1, start_year+i)
  return sum

def split_date(date, format='-'):
  return [int(n) for n in date.split(format)]

def date_diff(date1, date2):
  dayA, monthA, yearA = split_date(date1)
  dayB, monthB, yearB = split_date(date2)

  diff_days = 0
  all_days_start_year = day_of_year_from_start(dayA, monthA, yearA)
  all_days_end_year = day_of_year_from_end(dayB, monthB, yearB)

  if yearA == yearB:
    diff_days = all_days_end_year
  else:
    if yearB - yearA > 1:
      diff_days += calculate_n_year(yearA, yearB - yearA)
    diff_days += (all_days_start_year + all_days_end_year)

  return diff_days


# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 366 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)


731
76
367
366
366
365


Exercise 5.3 จากโปรแกรม 5.2 ให้เขียนฟังก์ชัน date_diff  เพิ่มเติม โดยให้มีการตรวจสอบ
วันที่ต้องเป็นวันที่ถูกต้องของเดือนนั้นๆ
เดือนต้องอยู่ระหว่าง 1-12
เดือนกุมภาพันธ์ของปีที่มี Leap Year เท่านั้นที่จะมี 29 วันได้
หากข้อมูล Input ผิดพลาด ให้ Return -1


In [ ]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
  year_str = str(year)
  year_only_first = year_str[0]+ "0"*(len(year_str[1:]))

  if year % 4 == 0 and year % 100 == 0 and year % 400 == 0:
    return True
  elif year % 4 == 0 and year % 100 != 0 and int(year_only_first) % 400 == 0:
    return True
  else:
    return False

def day_of_year_from_start(day, month, year):
  is_leap_year = leap_year(year)

  sum_of_days = 0

  if day == 1 and month == 1:
    sum_of_days += sum(days_in_month)
  else:
    sum_of_days += (days_in_month[month - 1] - day) + 1
    sum_of_days += sum(days_in_month[month:])

  if is_leap_year and month <= 2:
      sum_of_days += 1

  return sum_of_days

def day_of_year_from_end(day, month, year):
  is_leap_year = leap_year(year)

  sum_of_days = sum(days_in_month[:month - 1]) + day

  if is_leap_year and month > 2:
      sum_of_days += 1

  return sum_of_days

def calculate_n_year(start_year,year_count):
  sum = 0
  for i in range(1, year_count):
    sum += day_of_year_from_start(1, 1, start_year+i)
  return sum

def split_date(date, format='-'):
  list_date = [n for n in date.split(format)]
  error = -1

  if len(list_date) != 3:
    return error

  for i in range(len(list_date)):
    if not f"{list_date[i]}".isdigit():
      return error
    else:
      list_date[i] = int(list_date[i])

  day = list_date[0]
  month = list_date[1]
  year = list_date[2]

  if (1 < day > 31) or (0 < month > 12) or year < 1:
    return error
  elif day > days_in_month[month - 1]:
    return error
  else:
    return list_date

def date_diff(date1, date2):
  format_dateA, format_dateB = split_date(date1), split_date(date2)

  if format_dateA == -1 or format_dateB == -1:
    return -1

  dayA, monthA, yearA = format_dateA
  dayB, monthB, yearB = format_dateB

  diff_days = 0
  all_days_start_year = day_of_year_from_start(dayA, monthA, yearA)
  all_days_end_year = day_of_year_from_end(dayB, monthB, yearB)

  if yearA == yearB:
    diff_days = all_days_end_year
  else:
    if yearB - yearA > 1:
      diff_days += calculate_n_year(yearA, yearB - yearA)
    diff_days += (all_days_start_year + all_days_end_year)

  return diff_days

# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 366 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)

# ทดสอบกรณีข้อมูลไม่ถูกต้อง
print(date_diff("31-4-2023", "1-5-2023"))  # ควรได้ -1 (เดือนเมษายนมี 30 วัน)
print(date_diff("29-2-2023", "1-3-2023"))  # ควรได้ -1 (ปี 2023 ไม่ใช่ leap year)
print(date_diff("1-13-2023", "1-1-2024"))  # ควรได้ -1 (เดือนไม่ถูกต้อง)
print(date_diff("abc", "1-1-2024"))  # ควรได้ -1 (รูปแบบวันที่ไม่ถูกต้อง)

731
76
367
366
366
365
-1
-1
-1
-1


1.	ปลาหมอคางดำเพศเมีย 1 ตัว เมื่ออายุครบ 2 เดือน จะสามารถสืบพันธ์ได้ โดยระยะเวลาตั้งท้องจนถึง
วางไข่ของตัวเมียจะใช้เวลา 21 วัน และฟักในปากเพศผู้อีก 7 วัน (สามารถรวมเป็น 1 เดือนได้) โดยออกไข่ครั้งละ 300 ฟอง กำหนดให้ไข่ฟักเป็นเพศผู้และเพศเมียอย่างละครึ่ง และเมื่อวางไข่แล้วจะสามารถสืบพันธ์ต่อได้ทันที กำหนดให้ปลามีอายุ 5 ปี และปลาทั้งหมดจะตาย p% ทุก 1 เดือน จงหาว่าปลาหมอคางดำหลุดจากฟาร์ม n ตัวเป็นเพศผู้และเพศเมียอย่างละครึ่ง จงเขียนโปรแกรมรับค่า n และ p ให้แสดงผลจำนวนปลาทุก 3 เดือน เป็นเวลา 10 ปี ให้เขียนเป็นฟังก์ชัน ชื่อ simulate_fish_population()


In [ ]:
def fish_evolution(egg_and_fish, p, n, month):
  max_evo_fish = sum(egg_and_fish[1:])

  if month == 4:
    max_evo_fish += n

  merge = (max_evo_fish - (max_evo_fish * (p/100))) / 2

  return [merge * 300, egg_and_fish[0], max_evo_fish]

def minus_p_percent(lst, p):
  for i in range(len(lst)):
    if i == 0:
      continue
    lst[i] -= (lst[i]*(p/100))
  return lst

def print_every_3_month(lst, n, month):
  if month % 3 == 0:
    sum_of_max_evo_fish = int(sum(lst[1:]))

    if month == 3:
      all_fish = sum_of_max_evo_fish+n
      half_fish = int(all_fish / 2)
      print(half_fish, half_fish, sum_of_max_evo_fish+n)
    else:
      half_fish = int(sum_of_max_evo_fish / 2)
      print(half_fish, half_fish, sum_of_max_evo_fish)


def simulate_fish_population(n, p, months=3):
  egg = []
  month_count = 1
  fish_every_1_year = []

  while month_count <= 120:
    if len(egg) >= 3:
      egg = fish_evolution(egg, p, n, month_count)
    else:
      egg.insert(0, n/2 * 300)

    if len(egg) > 1:
      egg = minus_p_percent(egg, p)
    # print(egg)

    print_every_3_month(egg, n, month_count)

    if month_count % 12 == 0:
      fish_every_1_year.append(sum(egg[1:]))
    month_count += 1
  return fish_every_1_year

init_fish = 2
percent_of_death = 10

print("Men Women Sum_of_fish")
year1 = simulate_fish_population(init_fish, percent_of_death)


# ถ้าเริ่มต้นด้วยปลา 2 ตัว ตายเดือนละ 10%
# เดือนที่ 1 ไข่ 300 ไบ
# เดือนที่ 2 ไข่ 300 ใบ + ลูกปลา 270 ตัว
# เดือนที่ 3 ไข่ 300 ใบ + ลูกปลา 270 ตัว + ปลาโตเต็มวัย 243 ตัว + 2 = 515 ตัว

# ไข่มาจาก (515 - 10%) / 2  = 231.75
# 231.75 * 300 = 69525
# เดือนที่ 4 ไข่ 69525 + ลูกปลา 270 + ปลาโตเต็มวัย 463.5 ตัว = 733.5 ตัว

# ไข่มาจาก (733.5 - 10%) = 660.15 / 2  = 330.075
# 330.075 * 300 = 99022.5
# เดือนที่ 5 ไข่ 99022.5 + ลูกปลา 62572.5 + ปลาโตเต็มวัย 660.15 ตัว = 63232.65 ตัว


Men Women Sum_of_fish
257 257 515
73014 73014 146029
485861182 485861182 971722365
290701307043 290701307043 581402614086
967023600793641 967023600793641 1934047201587283
839342804887660160 839342804887660160 1678685609775320320
2010424752372296187904 2010424752372296187904 4020849504744592375808
2166441920716733096656896 2166441920716733096656896 4332883841433466193313792
4318205333537339829529870336 4318205333537339829529870336 8636410667074679659059740672
5305494436513294154880113442816 5305494436513294154880113442816 10610988873026588309760226885632
9489525997571311867423681299873792 9489525997571311867423681299873792 18979051995142623734847362599747584
12635962650273829801310793725166747648 12635962650273829801310793725166747648 25271925300547659602621587450333495296
21174979915848506482752914390590135730176 21174979915848506482752914390590135730176 42349959831697012965505828781180271460352
29625920337284343932309258846624338224873472 29625920337284343932309258846624338224873472 5

2.	ให้เขียน function find_mismatch ซึ่งรับ string มา 2 ค่า โดยจะส่งค่ากลับดังนี้
- 0 เมื่อ string ทั้ง 2 ตัว เหมือนกัน โดยไม่สนใจ case
- 1 เมื่อ string 1 จะเหมือน string 2 โดยการลบและ/หรือเพิ่มตัวอักษรเพียง 1 ตัว
- 2 เมื่อ string ไม่เข้าเกณฑ์ 0 หรือ 1


| String  1| 	String2	|ผลลัพธ์|
|----------|----------|------|
|Python|	Java	|2|
|book	 |  boot	|1|
|fan	 |  fun	  |1|
|sin	 | sink	  |1 เพราะเพิ่ม k ใน str2 แล้วจะเหมือนกัน
|Dog	 | dog	  |0
|poke	 | spoke	|1 เพิ่ม s ใน str2 แล้วเหมือนกัน
|poker |	poke	|1 ตัด r ใน str1 ออกแล้วเหมือนกัน






In [92]:
def count_same_char(word, diff_word):
  sum = 0
  checked_word = []
  for i in word:
    if i in diff_word and i not in checked_word:
      if word.count(i) > diff_word.count(i):
        sum += diff_word.count(i)
      else:
        sum += word.count(i)

      checked_word.append(i)

  return sum

def find_word_next(str1, str2):
  if str1[1:] == str2:
    return str1[0], "remove"
  if str1[0:-1] == str2:
    return str1[-1], "remove"
  if str2[1:] == str1:
    return str2[0], "add"
  if str2[0:-1] == str1:
    return str2[-1], "add"


def find_diff_word(str1, str2):
  s1, s2 = str1.lower(), str2.lower()
  lenS1, lenS2 = len(s1), len(s2)

  if abs(lenS1 - lenS2) == 1:
    result = find_word_next(s1, s2)
    if result != None:
      return result

  if (s1[:-1] == s2[:-1]) or (s1[1:] == s2[1:]):
    return "x", ""

  same_char_str1 = count_same_char(s1, s2)
  same_char_str2 = count_same_char(s2, s1)

  if abs(lenS1 - same_char_str1) == 1 and abs(lenS2 - same_char_str2) == 1:
    return "x", ""

  return "", ""

def find_mismatch(str1, str2):
  if str1.lower() == str2.lower():
    return 0

  diff, type_of_diff = find_diff_word(str1, str2)
  if len(diff) == 1:
    if type_of_diff == '':
      return 1
    return f'1 {type_of_diff} {diff}'

  return 2


wordA = ["Python", "book", "fan", "sin", "Dog", "poke", "poker"]
wordB = ["Java", "boot", "fun", "sink", "dog", "spoke", "poke"]

print("-"*35)
print("| String 1 ", " String2 ", '    ผลลัพธ์   |', sep='|')
print("-"*35)

for i in range(len(wordA)):
  result = find_mismatch(wordA[i], wordB[i])
  print(f'| {wordA[i]:<8} | {wordB[i]:<7} | {result:<10} |')
  print("-"*35)

-----------------------------------
| String 1 | String2 |    ผลลัพธ์   |
-----------------------------------
| Python   | Java    | 2          |
-----------------------------------
| book     | boot    | 1          |
-----------------------------------
| fan      | fun     | 1          |
-----------------------------------
| sin      | sink    | 1 add k    |
-----------------------------------
| Dog      | dog     | 0          |
-----------------------------------
| poke     | spoke   | 1 add s    |
-----------------------------------
| poker    | poke    | 1 remove r |
-----------------------------------


3.	จากข้อ 1 ให้เขียนฟังก์ชันชื่อ spelling_correction โดยรับ 2 argument ตัวแรกเป็นประโยค (string) และตัวที่ 2 เป็น list ของคำ (correct_spells) โดยฟังก์ชันนี้มีหน้าที่ตรวจสอบแต่ละ word ใน input string กับคำที่อยู่ใน correct_spells โดยค่าที่คืนกลับมาจะมีดังนี้ (พยายามเรียกใช้ฟังก์ชันในข้อ 1)
-	ถ้าคำที่อยู่ในประโยค ตรงกับคำที่อยู่ใน correct_spells ทุกอย่าง ก็จะ copy ไปที่ output string
-	ถ้าคำที่อยู่ในประโยค ต่างจากคำที่อยู่ใน correct_spells โดยต่างกัน 1 ตัวอักษร โดยการเปลี่ยน การเพิ่ม หรือการลบ 1 ตัวอักษร คำที่อยู่ในประโยคจะถูกเปลี่ยนโดยคำที่อยู่ใน correct_spells และนำไปใส่ output string
-	ถ้าคำที่ไม่พบในเงื่อนไขข้างต้นให้นำคำนั้นไปใส่ output string ได้เลย
-	คำที่ประกอบด้วย 1 หรือ 2 ตัวอักษรจะไม่ตรวจสอบ ให้นำคำนั้นไปใส่ output string ได้เลย
-	ถ้ามี 2 คำใน correct_spells ที่ตรงตามเงื่อนไข ให้ใช้คำแรก
-	ไม่สนใจตัวใหญ่ ตัวเล็ก
-	Input string จะมีได้เพียงอักษรภาษาอังกฤษเท่านั้น
-	ในแต่ละคำจะคั่นด้วย 1 space ถ้ามี space มากกว่านั้นให้ตัดออก และตัด space จากหัวท้ายประโยค

|ประโยค	|correct_spells	|output string |
|-------|---------------|-------------|
|Thes is the Firs cas	|[‘that’,’first’,’case’,’car’]|	thes is the first car|
|programming is fan and easy	|[‘programming’,’this’,’fun’,’easy’,book’]	|programming is fun and easy|
|Thes is vary essy	|[‘this’,’is’,’very’,’easy’]	|this is very easy|
|Wee ipve Pythen	|[‘we’,’live’,’ln’,’Python’]	|we live python|




In [128]:
def count_same_char(word, diff_word):
  sum = 0
  checked_word = []
  for i in word:
    if i in diff_word and i not in checked_word:
      if word.count(i) > diff_word.count(i):
        sum += diff_word.count(i)
      else:
        sum += word.count(i)

      checked_word.append(i)

  return sum

def find_word_next(str1, str2):
  if str1[1:] == str2:
    return str1[0], "remove"
  if str1[0:-1] == str2:
    return str1[-1], "remove"
  if str2[1:] == str1:
    return str2[0], "add"
  if str2[0:-1] == str1:
    return str2[-1], "add"


def find_diff_word(str1, str2):
  s1, s2 = str1.lower(), str2.lower()
  lenS1, lenS2 = len(s1), len(s2)

  if abs(lenS1 - lenS2) == 1:
    result = find_word_next(s1, s2)
    if result != None:
      return result

  if (s1[:-1] == s2[:-1]) or (s1[1:] == s2[1:]):
    return "x", ""

  same_char_str1 = count_same_char(s1, s2)
  same_char_str2 = count_same_char(s2, s1)

  if abs(lenS1 - same_char_str1) == 1 and abs(lenS2 - same_char_str2) == 1:
    return "x", ""

  return "", ""

def find_mismatch(str1, str2):
  if str1.lower() == str2.lower():
    return 0

  diff, type_of_diff = find_diff_word(str1, str2)
  if len(diff) == 1:
    return 1

  return 2

def check_and_format(input):
  is_eng = "abcdefghijklmnopqrstuvwxyz"
  list_word = input.split()

  for i in range(len(list_word)):
    for j in list_word[i].lower():
      if j not in is_eng:
        return -1
    list_word[i] = list_word[i].lower()

  return list_word

def spelling_correction(input_string, correct_spells):
  words = check_and_format(input_string)

  if words == -1:
    return "Error"

  output = ""

  for word in words:
    diff_one = []
    for correct_word in correct_spells:
      result = find_mismatch(word, correct_word)
      if result == 1:
        diff_one.append(correct_word)

    if len(diff_one) > 0:
      output += diff_one[-1] + " "
    else:
      output += word + " "

  return output.strip()


word = ["Thes is the Firs cas", "programming is fan and easy", "Thes is vary essy", "Wee ipve Pythen"]
correct_spells = [
  ['that', 'first', 'case', 'car'],
  ['programming', 'this','fun', 'easy', 'book'],
  ['this', 'is', 'very', 'easy'],
  ['we', 'live', 'ln', 'Python']
]

space = 112

print("-"*space)
print(f"| {'ประโยค':^30} ", f"{'correct_spells':^48}", f" {'output string':^27} |", sep='|')
print("-"*space)

for i in range(len(word)):
  result = spelling_correction(word[i], correct_spells[i])
  print(f'| {word[i]:<30} | {f"{correct_spells[i]}":<46} | {result:<27} |')
  print("-"*space)

----------------------------------------------------------------------------------------------------------------
|             ประโยค             |                 correct_spells                 |        output string        |
----------------------------------------------------------------------------------------------------------------
| Thes is the Firs cas           | ['that', 'first', 'case', 'car']               | thes is the first car       |
----------------------------------------------------------------------------------------------------------------
| programming is fan and easy    | ['programming', 'this', 'fun', 'easy', 'book'] | programming is fun and easy |
----------------------------------------------------------------------------------------------------------------
| Thes is vary essy              | ['this', 'is', 'very', 'easy']                 | this is very easy           |
--------------------------------------------------------------------------------------------

4. ให้เขียนฟังก์ชัน find_word_horizontal ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามแถวของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
	word='cat'
	find_word_horizontal(crosswords,word)
```

Output
   [2,1]


In [ ]:
def find_word_horizontal(crosswords, word):
    for i in range(len(crosswords)):
        for j in range(len(crosswords[i]) - (len(word) - 1)):
            n_word = ""
            for k in range(len(word)):
              n_word += crosswords[i][j+k]
            if n_word == word:
                return [i, j]
    return None

crosswords = [
    ['s', 'd', 'o', 'g'],
    ['c', 'u', 'c', 'm'],
    ['a', 'c', 'a', 't'],
    ['t', ' e', 't', 'k']
]

word = 'cat'

result = find_word_horizontal(crosswords, word)
print("Output",result)

Output [2, 1]


5. ให้เขียนฟังก์ชัน find_word_vertical ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามคอลัมน์ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

ตัวอย่าง
```
	crosswords=[['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t',' e','t','k']]
	word='cat'
	find_word_vertical(crosswords,word)
```

Output
   [1,0]


In [ ]:
def find_word_vertical(crosswords, word):
    for i in range(len(crosswords) - (len(word) - 1)):
        for j in range(len(crosswords[i])):
            n_word = ""
            for k in range(len(word)):
              n_word += crosswords[i+k][j]

            if n_word == word:
                return [i, j]
    return None

crosswords = [
    ['s', 'd', 'o', 'g'],
    ['c', 'u', 'c', 'm'],
    ['a', 'c', 'a', 't'],
    ['t', ' e', 't', 'k']
]

word = 'cat'

result = find_word_vertical(crosswords, word)
print("Output", result)

Output [1, 0]


6.	ให้เขียนฟังก์ชัน capitalize_word_in_crossword จะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตาม row และ column ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบจะเปลี่ยนเป็นตัวใหญ่และ และส่งคืน list ที่แก้ไขแล้ว แต่ถ้าไม่เจอจะส่ง list เดิมกลับมา ให้ใช้ฟังก์ชันตามข้อ 3 และ 4 ช่วย

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','x','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
```
จะส่งค่ากลับ
```
 [['s','d','o','g'],
  ['C','u','c','m'],
  ['A','x','a','t'],
  ['T','e','t','k']]
```
```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
จะส่งค่ากลับ                   
[['s','d','o','g'],
 ['c','u','c','m'],
 ['a','C','A','T'],
 ['t','e','t','k']]
```




In [ ]:
def find_word_horizontal(crosswords, word):
    for i in range(len(crosswords)):
        for j in range(len(crosswords[i]) - (len(word) - 1)):
            n_word = ""
            for k in range(len(word)):
              n_word += crosswords[i][j+k]
            if n_word == word:
                return [i, j]
    return None

def find_word_vertical(crosswords, word):
    for i in range(len(crosswords) - (len(word) - 1)):
        for j in range(len(crosswords[i])):
            n_word = ""
            for k in range(len(word)):
              n_word += crosswords[i+k][j]

            if n_word == word:
                return [i, j]
    return None

def capitalize_word_in_crossword(crosswords, word):
  h_index = find_word_horizontal(crosswords, word)
  if h_index != None:
    for i in range(len(word)):
      crosswords[h_index[0]][h_index[1]+i] = crosswords[h_index[0]][h_index[1]+i].upper()


  v_index = find_word_vertical(crosswords, word)
  if v_index != None:
    for i in range(len(word)):
      crosswords[v_index[0]+i][v_index[1]] = crosswords[v_index[0]+i][v_index[1]].upper()
  return crosswords


crosswords=[
    ['s','d','o','g'],
    ['c','u','c','m'],
    ['a','x','a','t'],
    ['t','e','t','k']
]

word='cat'
result = capitalize_word_in_crossword(crosswords,word)

for i in result:
  print(i)

['s', 'd', 'o', 'g']
['C', 'u', 'c', 'm']
['A', 'C', 'A', 'T']
['T', 'e', 't', 'k']
